// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/manciniraka/medioxe/internal/entity"
	service "github.com/manciniraka/medioxe/internal/service"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserRepository) CreateUser(user *entity.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserRepositoryMockRecorder) CreateUser(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserRepository)(nil).CreateUser), user)
}

// GetByEmail mocks base method.
func (m *MockUserRepository) GetByEmail(email string) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", email)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepositoryMockRecorder) GetByEmail(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepository)(nil).GetByEmail), email)
}

// GetByID mocks base method.
func (m *MockUserRepository) GetByID(id int) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryMockRecorder) GetByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepository)(nil).GetByID), id)
}

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockAuthService) Login(input service.LoginInput) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", input)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthServiceMockRecorder) Login(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthService)(nil).Login), input)
}

// Register mocks base method.
func (m *MockAuthService) Register(input service.RegisterInput) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", input)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockAuthServiceMockRecorder) Register(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAuthService)(nil).Register), input)
}

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// GetProfile mocks base method.
func (m *MockUserService) GetProfile(userID int) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfile", userID)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockUserServiceMockRecorder) GetProfile(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockUserService)(nil).GetProfile), userID)
}

// MockSpecialtyRepository is a mock of SpecialtyRepository interface.
type MockSpecialtyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSpecialtyRepositoryMockRecorder
}

// MockSpecialtyRepositoryMockRecorder is the mock recorder for MockSpecialtyRepository.
type MockSpecialtyRepositoryMockRecorder struct {
	mock *MockSpecialtyRepository
}

// NewMockSpecialtyRepository creates a new mock instance.
func NewMockSpecialtyRepository(ctrl *gomock.Controller) *MockSpecialtyRepository {
	mock := &MockSpecialtyRepository{ctrl: ctrl}
	mock.recorder = &MockSpecialtyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpecialtyRepository) EXPECT() *MockSpecialtyRepositoryMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockSpecialtyRepository) GetAll() ([]entity.Specialty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]entity.Specialty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockSpecialtyRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockSpecialtyRepository)(nil).GetAll))
}

// GetByID mocks base method.
func (m *MockSpecialtyRepository) GetByID(id int) (*entity.Specialty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*entity.Specialty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSpecialtyRepositoryMockRecorder) GetByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSpecialtyRepository)(nil).GetByID), id)
}

// GetByName mocks base method.
func (m *MockSpecialtyRepository) GetByName(name string) (*entity.Specialty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", name)
	ret0, _ := ret[0].(*entity.Specialty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockSpecialtyRepositoryMockRecorder) GetByName(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockSpecialtyRepository)(nil).GetByName), name)
}

// MockHospitalRepository is a mock of HospitalRepository interface.
type MockHospitalRepository struct {
	ctrl     *gomock.Controller
	recorder *MockHospitalRepositoryMockRecorder
}

// MockHospitalRepositoryMockRecorder is the mock recorder for MockHospitalRepository.
type MockHospitalRepositoryMockRecorder struct {
	mock *MockHospitalRepository
}

// NewMockHospitalRepository creates a new mock instance.
func NewMockHospitalRepository(ctrl *gomock.Controller) *MockHospitalRepository {
	mock := &MockHospitalRepository{ctrl: ctrl}
	mock.recorder = &MockHospitalRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHospitalRepository) EXPECT() *MockHospitalRepositoryMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockHospitalRepository) GetAll() ([]entity.Hospital, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]entity.Hospital)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockHospitalRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockHospitalRepository)(nil).GetAll))
}

// GetByID mocks base method.
func (m *MockHospitalRepository) GetByID(id int) (*entity.Hospital, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*entity.Hospital)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockHospitalRepositoryMockRecorder) GetByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockHospitalRepository)(nil).GetByID), id)
}

// MockDoctorRepository is a mock of DoctorRepository interface.
type MockDoctorRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDoctorRepositoryMockRecorder
}

// MockDoctorRepositoryMockRecorder is the mock recorder for MockDoctorRepository.
type MockDoctorRepositoryMockRecorder struct {
	mock *MockDoctorRepository
}

// NewMockDoctorRepository creates a new mock instance.
func NewMockDoctorRepository(ctrl *gomock.Controller) *MockDoctorRepository {
	mock := &MockDoctorRepository{ctrl: ctrl}
	mock.recorder = &MockDoctorRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDoctorRepository) EXPECT() *MockDoctorRepositoryMockRecorder {
	return m.recorder
}

// CreateDoctor mocks base method.
func (m *MockDoctorRepository) CreateDoctor(profile *entity.DoctorProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDoctor", profile)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDoctor indicates an expected call of CreateDoctor.
func (mr *MockDoctorRepositoryMockRecorder) CreateDoctor(profile interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDoctor", reflect.TypeOf((*MockDoctorRepository)(nil).CreateDoctor), profile)
}

// GetAll mocks base method.
func (m *MockDoctorRepository) GetAll() ([]entity.DoctorProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]entity.DoctorProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockDoctorRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockDoctorRepository)(nil).GetAll))
}

// GetByHospitalID mocks base method.
func (m *MockDoctorRepository) GetByHospitalID(hospitalID int) ([]entity.DoctorProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByHospitalID", hospitalID)
	ret0, _ := ret[0].([]entity.DoctorProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByHospitalID indicates an expected call of GetByHospitalID.
func (mr *MockDoctorRepositoryMockRecorder) GetByHospitalID(hospitalID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByHospitalID", reflect.TypeOf((*MockDoctorRepository)(nil).GetByHospitalID), hospitalID)
}

// GetByID mocks base method.
func (m *MockDoctorRepository) GetByID(id int) (*entity.DoctorProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*entity.DoctorProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDoctorRepositoryMockRecorder) GetByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDoctorRepository)(nil).GetByID), id)
}

// GetBySpecialtyID mocks base method.
func (m *MockDoctorRepository) GetBySpecialtyID(specialtyID int) ([]entity.DoctorProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySpecialtyID", specialtyID)
	ret0, _ := ret[0].([]entity.DoctorProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySpecialtyID indicates an expected call of GetBySpecialtyID.
func (mr *MockDoctorRepositoryMockRecorder) GetBySpecialtyID(specialtyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySpecialtyID", reflect.TypeOf((*MockDoctorRepository)(nil).GetBySpecialtyID), specialtyID)
}

// GetByUserID mocks base method.
func (m *MockDoctorRepository) GetByUserID(userID int) (*entity.DoctorProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", userID)
	ret0, _ := ret[0].(*entity.DoctorProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockDoctorRepositoryMockRecorder) GetByUserID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockDoctorRepository)(nil).GetByUserID), userID)
}

// UpdateDoctor mocks base method.
func (m *MockDoctorRepository) UpdateDoctor(profile *entity.DoctorProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDoctor", profile)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDoctor indicates an expected call of UpdateDoctor.
func (mr *MockDoctorRepositoryMockRecorder) UpdateDoctor(profile interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDoctor", reflect.TypeOf((*MockDoctorRepository)(nil).UpdateDoctor), profile)
}

// MockSymptomAnalysisRepository is a mock of SymptomAnalysisRepository interface.
type MockSymptomAnalysisRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSymptomAnalysisRepositoryMockRecorder
}

// MockSymptomAnalysisRepositoryMockRecorder is the mock recorder for MockSymptomAnalysisRepository.
type MockSymptomAnalysisRepositoryMockRecorder struct {
	mock *MockSymptomAnalysisRepository
}

// NewMockSymptomAnalysisRepository creates a new mock instance.
func NewMockSymptomAnalysisRepository(ctrl *gomock.Controller) *MockSymptomAnalysisRepository {
	mock := &MockSymptomAnalysisRepository{ctrl: ctrl}
	mock.recorder = &MockSymptomAnalysisRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSymptomAnalysisRepository) EXPECT() *MockSymptomAnalysisRepositoryMockRecorder {
	return m.recorder
}

// CreateSymptomAnalysis mocks base method.
func (m *MockSymptomAnalysisRepository) CreateSymptomAnalysis(analysis *entity.SymptomAnalysis) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSymptomAnalysis", analysis)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSymptomAnalysis indicates an expected call of CreateSymptomAnalysis.
func (mr *MockSymptomAnalysisRepositoryMockRecorder) CreateSymptomAnalysis(analysis interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSymptomAnalysis", reflect.TypeOf((*MockSymptomAnalysisRepository)(nil).CreateSymptomAnalysis), analysis)
}

// GetByID mocks base method.
func (m *MockSymptomAnalysisRepository) GetByID(id int) (*entity.SymptomAnalysis, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*entity.SymptomAnalysis)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSymptomAnalysisRepositoryMockRecorder) GetByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSymptomAnalysisRepository)(nil).GetByID), id)
}

// MockDoctorService is a mock of DoctorService interface.
type MockDoctorService struct {
	ctrl     *gomock.Controller
	recorder *MockDoctorServiceMockRecorder
}

// MockDoctorServiceMockRecorder is the mock recorder for MockDoctorService.
type MockDoctorServiceMockRecorder struct {
	mock *MockDoctorService
}

// NewMockDoctorService creates a new mock instance.
func NewMockDoctorService(ctrl *gomock.Controller) *MockDoctorService {
	mock := &MockDoctorService{ctrl: ctrl}
	mock.recorder = &MockDoctorServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDoctorService) EXPECT() *MockDoctorServiceMockRecorder {
	return m.recorder
}

// ActivateDoctor mocks base method.
func (m *MockDoctorService) ActivateDoctor(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateDoctor", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateDoctor indicates an expected call of ActivateDoctor.
func (mr *MockDoctorServiceMockRecorder) ActivateDoctor(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateDoctor", reflect.TypeOf((*MockDoctorService)(nil).ActivateDoctor), id)
}

// CreateDoctor mocks base method.
func (m *MockDoctorService) CreateDoctor(input service.CreateDoctorInput) (*entity.DoctorProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDoctor", input)
	ret0, _ := ret[0].(*entity.DoctorProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDoctor indicates an expected call of CreateDoctor.
func (mr *MockDoctorServiceMockRecorder) CreateDoctor(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDoctor", reflect.TypeOf((*MockDoctorService)(nil).CreateDoctor), input)
}

// DeactivateDoctor mocks base method.
func (m *MockDoctorService) DeactivateDoctor(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateDoctor", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateDoctor indicates an expected call of DeactivateDoctor.
func (mr *MockDoctorServiceMockRecorder) DeactivateDoctor(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateDoctor", reflect.TypeOf((*MockDoctorService)(nil).DeactivateDoctor), id)
}

// GetDoctorByID mocks base method.
func (m *MockDoctorService) GetDoctorByID(id int) (*entity.DoctorProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDoctorByID", id)
	ret0, _ := ret[0].(*entity.DoctorProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDoctorByID indicates an expected call of GetDoctorByID.
func (mr *MockDoctorServiceMockRecorder) GetDoctorByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDoctorByID", reflect.TypeOf((*MockDoctorService)(nil).GetDoctorByID), id)
}

// GetDoctors mocks base method.
func (m *MockDoctorService) GetDoctors(specialtyID, hospitalID int) ([]entity.DoctorProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDoctors", specialtyID, hospitalID)
	ret0, _ := ret[0].([]entity.DoctorProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDoctors indicates an expected call of GetDoctors.
func (mr *MockDoctorServiceMockRecorder) GetDoctors(specialtyID, hospitalID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDoctors", reflect.TypeOf((*MockDoctorService)(nil).GetDoctors), specialtyID, hospitalID)
}

// GetMyProfile mocks base method.
func (m *MockDoctorService) GetMyProfile(userID int) (*entity.DoctorProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMyProfile", userID)
	ret0, _ := ret[0].(*entity.DoctorProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMyProfile indicates an expected call of GetMyProfile.
func (mr *MockDoctorServiceMockRecorder) GetMyProfile(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyProfile", reflect.TypeOf((*MockDoctorService)(nil).GetMyProfile), userID)
}

// UpdateDoctor mocks base method.
func (m *MockDoctorService) UpdateDoctor(id int, input service.UpdateDoctorInput) (*entity.DoctorProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDoctor", id, input)
	ret0, _ := ret[0].(*entity.DoctorProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDoctor indicates an expected call of UpdateDoctor.
func (mr *MockDoctorServiceMockRecorder) UpdateDoctor(id, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDoctor", reflect.TypeOf((*MockDoctorService)(nil).UpdateDoctor), id, input)
}

// UpdateMyProfile mocks base method.
func (m *MockDoctorService) UpdateMyProfile(userID int, input service.UpdateMyProfileInput) (*entity.DoctorProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMyProfile", userID, input)
	ret0, _ := ret[0].(*entity.DoctorProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMyProfile indicates an expected call of UpdateMyProfile.
func (mr *MockDoctorServiceMockRecorder) UpdateMyProfile(userID, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMyProfile", reflect.TypeOf((*MockDoctorService)(nil).UpdateMyProfile), userID, input)
}

// MockScheduleRepository is a mock of ScheduleRepository interface.
type MockScheduleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockScheduleRepositoryMockRecorder
}

// MockScheduleRepositoryMockRecorder is the mock recorder for MockScheduleRepository.
type MockScheduleRepositoryMockRecorder struct {
	mock *MockScheduleRepository
}

// NewMockScheduleRepository creates a new mock instance.
func NewMockScheduleRepository(ctrl *gomock.Controller) *MockScheduleRepository {
	mock := &MockScheduleRepository{ctrl: ctrl}
	mock.recorder = &MockScheduleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduleRepository) EXPECT() *MockScheduleRepositoryMockRecorder {
	return m.recorder
}

// CreateSchedule mocks base method.
func (m *MockScheduleRepository) CreateSchedule(schedule *entity.Schedule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSchedule", schedule)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSchedule indicates an expected call of CreateSchedule.
func (mr *MockScheduleRepositoryMockRecorder) CreateSchedule(schedule interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSchedule", reflect.TypeOf((*MockScheduleRepository)(nil).CreateSchedule), schedule)
}

// DeleteSchedule mocks base method.
func (m *MockScheduleRepository) DeleteSchedule(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSchedule", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSchedule indicates an expected call of DeleteSchedule.
func (mr *MockScheduleRepositoryMockRecorder) DeleteSchedule(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSchedule", reflect.TypeOf((*MockScheduleRepository)(nil).DeleteSchedule), id)
}

// GetByDoctorID mocks base method.
func (m *MockScheduleRepository) GetByDoctorID(doctorID int) ([]entity.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDoctorID", doctorID)
	ret0, _ := ret[0].([]entity.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDoctorID indicates an expected call of GetByDoctorID.
func (mr *MockScheduleRepositoryMockRecorder) GetByDoctorID(doctorID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDoctorID", reflect.TypeOf((*MockScheduleRepository)(nil).GetByDoctorID), doctorID)
}

// GetByID mocks base method.
func (m *MockScheduleRepository) GetByID(id int) (*entity.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*entity.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockScheduleRepositoryMockRecorder) GetByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockScheduleRepository)(nil).GetByID), id)
}

// GetDoctorsBySpecialtyAndTime mocks base method.
func (m *MockScheduleRepository) GetDoctorsBySpecialtyAndTime(specialtyID int, startTime, endTime string) ([]entity.DoctorProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDoctorsBySpecialtyAndTime", specialtyID, startTime, endTime)
	ret0, _ := ret[0].([]entity.DoctorProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDoctorsBySpecialtyAndTime indicates an expected call of GetDoctorsBySpecialtyAndTime.
func (mr *MockScheduleRepositoryMockRecorder) GetDoctorsBySpecialtyAndTime(specialtyID, startTime, endTime interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDoctorsBySpecialtyAndTime", reflect.TypeOf((*MockScheduleRepository)(nil).GetDoctorsBySpecialtyAndTime), specialtyID, startTime, endTime)
}

// UpdateSchedule mocks base method.
func (m *MockScheduleRepository) UpdateSchedule(schedule *entity.Schedule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSchedule", schedule)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSchedule indicates an expected call of UpdateSchedule.
func (mr *MockScheduleRepositoryMockRecorder) UpdateSchedule(schedule interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSchedule", reflect.TypeOf((*MockScheduleRepository)(nil).UpdateSchedule), schedule)
}

// MockScheduleService is a mock of ScheduleService interface.
type MockScheduleService struct {
	ctrl     *gomock.Controller
	recorder *MockScheduleServiceMockRecorder
}

// MockScheduleServiceMockRecorder is the mock recorder for MockScheduleService.
type MockScheduleServiceMockRecorder struct {
	mock *MockScheduleService
}

// NewMockScheduleService creates a new mock instance.
func NewMockScheduleService(ctrl *gomock.Controller) *MockScheduleService {
	mock := &MockScheduleService{ctrl: ctrl}
	mock.recorder = &MockScheduleServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduleService) EXPECT() *MockScheduleServiceMockRecorder {
	return m.recorder
}

// CreateSchedule mocks base method.
func (m *MockScheduleService) CreateSchedule(userID int, input service.CreateScheduleInput) (*entity.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSchedule", userID, input)
	ret0, _ := ret[0].(*entity.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSchedule indicates an expected call of CreateSchedule.
func (mr *MockScheduleServiceMockRecorder) CreateSchedule(userID, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSchedule", reflect.TypeOf((*MockScheduleService)(nil).CreateSchedule), userID, input)
}

// DeleteSchedule mocks base method.
func (m *MockScheduleService) DeleteSchedule(userID, scheduleID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSchedule", userID, scheduleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSchedule indicates an expected call of DeleteSchedule.
func (mr *MockScheduleServiceMockRecorder) DeleteSchedule(userID, scheduleID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSchedule", reflect.TypeOf((*MockScheduleService)(nil).DeleteSchedule), userID, scheduleID)
}

// GetDoctorSchedules mocks base method.
func (m *MockScheduleService) GetDoctorSchedules(doctorID int) ([]entity.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDoctorSchedules", doctorID)
	ret0, _ := ret[0].([]entity.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDoctorSchedules indicates an expected call of GetDoctorSchedules.
func (mr *MockScheduleServiceMockRecorder) GetDoctorSchedules(doctorID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDoctorSchedules", reflect.TypeOf((*MockScheduleService)(nil).GetDoctorSchedules), doctorID)
}

// GetMySchedules mocks base method.
func (m *MockScheduleService) GetMySchedules(userID int) ([]entity.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMySchedules", userID)
	ret0, _ := ret[0].([]entity.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMySchedules indicates an expected call of GetMySchedules.
func (mr *MockScheduleServiceMockRecorder) GetMySchedules(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMySchedules", reflect.TypeOf((*MockScheduleService)(nil).GetMySchedules), userID)
}

// UpdateSchedule mocks base method.
func (m *MockScheduleService) UpdateSchedule(userID, scheduleID int, input service.UpdateScheduleInput) (*entity.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSchedule", userID, scheduleID, input)
	ret0, _ := ret[0].(*entity.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSchedule indicates an expected call of UpdateSchedule.
func (mr *MockScheduleServiceMockRecorder) UpdateSchedule(userID, scheduleID, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSchedule", reflect.TypeOf((*MockScheduleService)(nil).UpdateSchedule), userID, scheduleID, input)
}

// MockAppointmentRepository is a mock of AppointmentRepository interface.
type MockAppointmentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAppointmentRepositoryMockRecorder
}

// MockAppointmentRepositoryMockRecorder is the mock recorder for MockAppointmentRepository.
type MockAppointmentRepositoryMockRecorder struct {
	mock *MockAppointmentRepository
}

// NewMockAppointmentRepository creates a new mock instance.
func NewMockAppointmentRepository(ctrl *gomock.Controller) *MockAppointmentRepository {
	mock := &MockAppointmentRepository{ctrl: ctrl}
	mock.recorder = &MockAppointmentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppointmentRepository) EXPECT() *MockAppointmentRepositoryMockRecorder {
	return m.recorder
}

// CreateAppointment mocks base method.
func (m *MockAppointmentRepository) CreateAppointment(appointment *entity.Appointment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAppointment", appointment)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAppointment indicates an expected call of CreateAppointment.
func (mr *MockAppointmentRepositoryMockRecorder) CreateAppointment(appointment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAppointment", reflect.TypeOf((*MockAppointmentRepository)(nil).CreateAppointment), appointment)
}

// GetByDoctorID mocks base method.
func (m *MockAppointmentRepository) GetByDoctorID(doctorID int) ([]entity.Appointment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDoctorID", doctorID)
	ret0, _ := ret[0].([]entity.Appointment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDoctorID indicates an expected call of GetByDoctorID.
func (mr *MockAppointmentRepositoryMockRecorder) GetByDoctorID(doctorID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDoctorID", reflect.TypeOf((*MockAppointmentRepository)(nil).GetByDoctorID), doctorID)
}

// GetByID mocks base method.
func (m *MockAppointmentRepository) GetByID(id int) (*entity.Appointment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*entity.Appointment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAppointmentRepositoryMockRecorder) GetByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAppointmentRepository)(nil).GetByID), id)
}

// GetByPatientID mocks base method.
func (m *MockAppointmentRepository) GetByPatientID(patientID int) ([]entity.Appointment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPatientID", patientID)
	ret0, _ := ret[0].([]entity.Appointment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPatientID indicates an expected call of GetByPatientID.
func (mr *MockAppointmentRepositoryMockRecorder) GetByPatientID(patientID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPatientID", reflect.TypeOf((*MockAppointmentRepository)(nil).GetByPatientID), patientID)
}

// UpdateAppointment mocks base method.
func (m *MockAppointmentRepository) UpdateAppointment(appointment *entity.Appointment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAppointment", appointment)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAppointment indicates an expected call of UpdateAppointment.
func (mr *MockAppointmentRepositoryMockRecorder) UpdateAppointment(appointment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAppointment", reflect.TypeOf((*MockAppointmentRepository)(nil).UpdateAppointment), appointment)
}

// MockAppointmentHistoryRepository is a mock of AppointmentHistoryRepository interface.
type MockAppointmentHistoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAppointmentHistoryRepositoryMockRecorder
}

// MockAppointmentHistoryRepositoryMockRecorder is the mock recorder for MockAppointmentHistoryRepository.
type MockAppointmentHistoryRepositoryMockRecorder struct {
	mock *MockAppointmentHistoryRepository
}

// NewMockAppointmentHistoryRepository creates a new mock instance.
func NewMockAppointmentHistoryRepository(ctrl *gomock.Controller) *MockAppointmentHistoryRepository {
	mock := &MockAppointmentHistoryRepository{ctrl: ctrl}
	mock.recorder = &MockAppointmentHistoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppointmentHistoryRepository) EXPECT() *MockAppointmentHistoryRepositoryMockRecorder {
	return m.recorder
}

// CreateAppointmentHistory mocks base method.
func (m *MockAppointmentHistoryRepository) CreateAppointmentHistory(history *entity.AppointmentHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAppointmentHistory", history)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAppointmentHistory indicates an expected call of CreateAppointmentHistory.
func (mr *MockAppointmentHistoryRepositoryMockRecorder) CreateAppointmentHistory(history interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAppointmentHistory", reflect.TypeOf((*MockAppointmentHistoryRepository)(nil).CreateAppointmentHistory), history)
}

// GetAll mocks base method.
func (m *MockAppointmentHistoryRepository) GetAll() ([]entity.AppointmentHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]entity.AppointmentHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockAppointmentHistoryRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockAppointmentHistoryRepository)(nil).GetAll))
}

// GetByAppointmentID mocks base method.
func (m *MockAppointmentHistoryRepository) GetByAppointmentID(appointmentID int) ([]entity.AppointmentHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAppointmentID", appointmentID)
	ret0, _ := ret[0].([]entity.AppointmentHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAppointmentID indicates an expected call of GetByAppointmentID.
func (mr *MockAppointmentHistoryRepositoryMockRecorder) GetByAppointmentID(appointmentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAppointmentID", reflect.TypeOf((*MockAppointmentHistoryRepository)(nil).GetByAppointmentID), appointmentID)
}

// MockAppointmentService is a mock of AppointmentService interface.
type MockAppointmentService struct {
	ctrl     *gomock.Controller
	recorder *MockAppointmentServiceMockRecorder
}

// MockAppointmentServiceMockRecorder is the mock recorder for MockAppointmentService.
type MockAppointmentServiceMockRecorder struct {
	mock *MockAppointmentService
}

// NewMockAppointmentService creates a new mock instance.
func NewMockAppointmentService(ctrl *gomock.Controller) *MockAppointmentService {
	mock := &MockAppointmentService{ctrl: ctrl}
	mock.recorder = &MockAppointmentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppointmentService) EXPECT() *MockAppointmentServiceMockRecorder {
	return m.recorder
}

// CancelAppointment mocks base method.
func (m *MockAppointmentService) CancelAppointment(userID, appointmentID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelAppointment", userID, appointmentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelAppointment indicates an expected call of CancelAppointment.
func (mr *MockAppointmentServiceMockRecorder) CancelAppointment(userID, appointmentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelAppointment", reflect.TypeOf((*MockAppointmentService)(nil).CancelAppointment), userID, appointmentID)
}

// CompleteAppointment mocks base method.
func (m *MockAppointmentService) CompleteAppointment(userID, appointmentID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteAppointment", userID, appointmentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteAppointment indicates an expected call of CompleteAppointment.
func (mr *MockAppointmentServiceMockRecorder) CompleteAppointment(userID, appointmentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteAppointment", reflect.TypeOf((*MockAppointmentService)(nil).CompleteAppointment), userID, appointmentID)
}

// ConfirmAppointment mocks base method.
func (m *MockAppointmentService) ConfirmAppointment(userID, appointmentID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmAppointment", userID, appointmentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmAppointment indicates an expected call of ConfirmAppointment.
func (mr *MockAppointmentServiceMockRecorder) ConfirmAppointment(userID, appointmentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmAppointment", reflect.TypeOf((*MockAppointmentService)(nil).ConfirmAppointment), userID, appointmentID)
}

// CreateAppointment mocks base method.
func (m *MockAppointmentService) CreateAppointment(patientID int, input service.CreateAppointmentInput) (*entity.Appointment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAppointment", patientID, input)
	ret0, _ := ret[0].(*entity.Appointment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAppointment indicates an expected call of CreateAppointment.
func (mr *MockAppointmentServiceMockRecorder) CreateAppointment(patientID, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAppointment", reflect.TypeOf((*MockAppointmentService)(nil).CreateAppointment), patientID, input)
}

// GetAll mocks base method.
func (m *MockAppointmentService) GetAll() ([]entity.AppointmentHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]entity.AppointmentHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockAppointmentServiceMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockAppointmentService)(nil).GetAll))
}

// GetAppointmentHistory mocks base method.
func (m *MockAppointmentService) GetAppointmentHistory(appointmentID int) ([]entity.AppointmentHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppointmentHistory", appointmentID)
	ret0, _ := ret[0].([]entity.AppointmentHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppointmentHistory indicates an expected call of GetAppointmentHistory.
func (mr *MockAppointmentServiceMockRecorder) GetAppointmentHistory(appointmentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppointmentHistory", reflect.TypeOf((*MockAppointmentService)(nil).GetAppointmentHistory), appointmentID)
}

// GetDoctorAppointments mocks base method.
func (m *MockAppointmentService) GetDoctorAppointments(userID int) ([]entity.Appointment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDoctorAppointments", userID)
	ret0, _ := ret[0].([]entity.Appointment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDoctorAppointments indicates an expected call of GetDoctorAppointments.
func (mr *MockAppointmentServiceMockRecorder) GetDoctorAppointments(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDoctorAppointments", reflect.TypeOf((*MockAppointmentService)(nil).GetDoctorAppointments), userID)
}

// GetMyAppointments mocks base method.
func (m *MockAppointmentService) GetMyAppointments(patientID int) ([]entity.Appointment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMyAppointments", patientID)
	ret0, _ := ret[0].([]entity.Appointment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMyAppointments indicates an expected call of GetMyAppointments.
func (mr *MockAppointmentServiceMockRecorder) GetMyAppointments(patientID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyAppointments", reflect.TypeOf((*MockAppointmentService)(nil).GetMyAppointments), patientID)
}

// MockNotificationRepository is a mock of NotificationRepository interface.
type MockNotificationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationRepositoryMockRecorder
}

// MockNotificationRepositoryMockRecorder is the mock recorder for MockNotificationRepository.
type MockNotificationRepositoryMockRecorder struct {
	mock *MockNotificationRepository
}

// NewMockNotificationRepository creates a new mock instance.
func NewMockNotificationRepository(ctrl *gomock.Controller) *MockNotificationRepository {
	mock := &MockNotificationRepository{ctrl: ctrl}
	mock.recorder = &MockNotificationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationRepository) EXPECT() *MockNotificationRepositoryMockRecorder {
	return m.recorder
}

// SendEmail mocks base method.
func (m *MockNotificationRepository) SendEmail(toName, toEmail, subject, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmail", toName, toEmail, subject, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEmail indicates an expected call of SendEmail.
func (mr *MockNotificationRepositoryMockRecorder) SendEmail(toName, toEmail, subject, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmail", reflect.TypeOf((*MockNotificationRepository)(nil).SendEmail), toName, toEmail, subject, message)
}

// MockAIService is a mock of AIService interface.
type MockAIService struct {
	ctrl     *gomock.Controller
	recorder *MockAIServiceMockRecorder
}

// MockAIServiceMockRecorder is the mock recorder for MockAIService.
type MockAIServiceMockRecorder struct {
	mock *MockAIService
}

// NewMockAIService creates a new mock instance.
func NewMockAIService(ctrl *gomock.Controller) *MockAIService {
	mock := &MockAIService{ctrl: ctrl}
	mock.recorder = &MockAIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAIService) EXPECT() *MockAIServiceMockRecorder {
	return m.recorder
}

// AnalyzeSymptoms mocks base method.
func (m *MockAIService) AnalyzeSymptoms(patientID int, input service.SymptomAnalysisInput) (*service.SymptomAnalysisResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnalyzeSymptoms", patientID, input)
	ret0, _ := ret[0].(*service.SymptomAnalysisResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AnalyzeSymptoms indicates an expected call of AnalyzeSymptoms.
func (mr *MockAIServiceMockRecorder) AnalyzeSymptoms(patientID, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnalyzeSymptoms", reflect.TypeOf((*MockAIService)(nil).AnalyzeSymptoms), patientID, input)
}
